config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  get    'signup'  => 'users#new'
  post   'users'   => 'users#create'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get '/public_arenas/:status' => 'welcome#show'
  get '/welcome' => 'welcome#index'
  get '/about' => 'about#index'

    resources :users do
      resources :videos, only: [:create, :new, :edit, :update, :destroy]
    end

    resources :videos do
      resources :votes
      resources :public_arenas, only: [:new, :edit, :create, :show, :update]
  end

  mount Sidekiq::Web, at: '/sidekiq'

  root 'sessions#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index #research how to take thumbnail of video
   if current_user
     @user = current_user
   end
   @public_arenas = PublicArena.all
   @video = Video.new
   @challenger_videos = PublicArena.all_challenger_videos
   render "index"
  end


#all you need to do is make sure that you get something tht ends in @challenger videos
# @challenger videos will be a collection of videos that have a public arena who's status is either 'open' 'closed' or 'in_battle'

  def show
    @user = current_user
    all_challenges = PublicArena.all_challenger_videos
    @battle_videos = []
    @closed_videos = []
    @open_videos = []
    @video = Video.new

    all_challenges.map do |vid|
      if params[:status] == "open" && vid.public_arena_as_challenger.open?
        @open_videos << vid
      elsif params[:status] == "in_battle" && vid.public_arena_as_challenger.in_battle?
        @battle_videos << vid
      elsif params[:status] == "closed" && vid.public_arena_as_challenger.close?
        @closed_videos << vid
      end
    end
  end
end

app/views/welcome/_status.html.erb
<div id="challenger_videos">
  <li >
          <table id="index-video" class="table-responsive">
            <th id="index-status">TopThat Categories
            </th>
            <tr>
              <td class="index-open" >
                Awaiting A Challenger:
              </td>
            </tr>
            <tr>
              <td>
                <p>Enter the arena!<br>Upload a video to accept challenge</p>
              </td>
            </tr>
            <tr>
              <td class="index-in-battle" >
                In Battle:
              </td>
            </tr>
            <tr>
              <td>
                <p>View the arena!<br>Vote for your favorite video</p>
              </td>
            </tr>
            <tr>
              <td class="index-close" >
                Battles of Yesteryear:
              </td>
            </tr>
            <tr>
              <td>
                <p>Review the battle!<br>View previous battles</p>
              </td>
            </tr>

            <tr>
              <td  class="index-view-btn">
                <button type="button" class = "btn btn-index index-open"><%= link_to 'About TopThat', "/about" %></button>
              </td>
            </tr>

          </table>
        </li>
  <%if @open_videos != [] %>

      <%@open_videos.reverse.each do |video|%>
        <li >
          <table id="index-video" class="table-responsive">
            <th id="index-status" class="index-open" colspan="2">AWAITING A CHALLENGER
            </th>
            <tr>
              <td style="height:27px"></td>
              <td></td>
            </tr>
            <tr>
              <td>
                <video width="120" height="60">
                  <source src= <%=video.data_content %> type="video/mp4"/>
                  </video>
                </td>
                <td>
                  <div class="index-open-topthatlogo text-center">
                    <%= image_tag("topthatlogo3.png", width: "60", height: "60") %>
                  </div>
                </td>
              </tr>
              <tr>
                <td colspan="2" class="centered" >
                  <button type="button" class="versus round">VS</button>
                </td>
              </tr>
              <tr>
                <td><%= video.title %></td>
                <td class="centered"><i>Can you top that?</i>
                </td>
              </tr>
              <tr>
                <td><%= image_tag(video.user.avatar, width: "30", height: "30")%> <%= link_to video.user.username, user_path(video.user)%>
                </td>
                <td>
                </td>
              </tr>
             <tr>
              <td style="height:27px"></td>
              <td></td>
            </tr>
              <tr>
                <td colspan="2" class="index-view-btn">
                  <button type="button" class = "btn btn-index index-open"><%= link_to 'Step into the Arena', video_public_arena_path(video,video.public_arena_as_challenger) %></button>
                </td>
              </tr>

            </table>
        </li>
          <% end %>

<% elsif @battle_videos != [] %>

      <%@battle_videos.reverse.each do |video|%>
        <%public_arena = video.public_arena_as_challenger%>
        <li >
            <table id="index-video" class="table-responsive">
              <th id="index-status" class="index-in-battle" colspan="2">IN BATTLE
              </th>
              <tr>
                <td>
                  <video width="120" height="60">
                    <source src= <%=public_arena.challenger_video.data_content %> type="video/mp4"/>
                    </video>
                </td>
                <td>
                  <video width="120" height="60">
                    <source src= <%=public_arena.challengee_video.data_content %> type="video/mp4"/>
                      </video>
                </td>
              </tr>
              <tr>
                <td colspan="2" class="centered" >
                      <button type="button" class="versus round">VS</button>
                </td>
              </tr>
              <tr>
                <td><%= video.title %></td>
                <td><%= public_arena.challengee_video.title %></td>
              </tr>
              <tr>
                <td><%= image_tag(video.user.avatar, width: "30", height: "30")%> <%= link_to video.user.username, user_path(video.user)%>
                </td>
                <td><%= image_tag(public_arena.challengee_video.user.avatar, width: "30", height: "30")%> <%= link_to public_arena.challengee_video.user.username, user_path(public_arena.challengee_video.user)%>
                </td>
              </tr>
              <tr>
                <td>Votes: <%= video.votes.count%>
                </td>
                <td>Votes: <%= public_arena.challengee_video.votes.count%>
                </td>
              </tr>
              <tr>
                <td colspan="2" class="index-view-btn">
                      <button type="button" class="btn btn-index index-in-battle"><%= link_to 'View Arena', video_public_arena_path(video,video.public_arena_as_challenger) %></button>
                </td>
              </tr>

            </table>
        </li>
              <% end %>


<% elsif @closed_videos != [] %>

      <%@closed_videos.reverse.each do |video|%>
      <%public_arena = video.public_arena_as_challenger%>
      <li >
            <table id="index-video" class="table-responsive">
              <th id="index-status" class="index-close" colspan="2">CLOSED
              </th>
              <tr>
                <td class="index-winner" >
                  <% if public_arena.challengee_video.winner %> TopThat Winner!
                  <% elsif public_arena.tie? %><i>Tied</i>
                  <% end %>
                </td>
                <td class="index-winner" >
                  <% if public_arena.challenger_video.winner %> TopThat Winner!
                  <% elsif public_arena.tie? %><i>Tied</i>
                  <% end %>
                </td>
              </tr>

              <tr>
                <td>
                  <div class="wrapper">
                    <video width="120" height="60">
                      <source src= <%= video.data_content %> type="video/mp4"/>
                      </video>
                    </div>
                  </td>
                  <td>
                    <div class="wrapper">
                      <video width="120" height="60">
                        <source src= <%= public_arena.challengee_video.data_content %> type="video/mp4"/>
                        </video>
                      </div>
                    </td>
                  </tr>

                  <tr>
                    <td colspan="2" class="centered" >
                      <button type="button" class="versus round">VS</button>
                    </td>
                  </tr>

                  <tr>
                    <td ><%= video.title %></td>
                    <td ><%= public_arena.challengee_video.title %></td>
                  </tr>

                  <tr>
                    <td ><%= image_tag(video.user.avatar, width: "30", height: "30")%> <%= link_to video.user.username, user_path(video.user)%>
                    </td>
                    <td ><%= image_tag(public_arena.challengee_video.user.avatar, width: "30", height: "30")%> <%= link_to public_arena.challengee_video.user.username, user_path(public_arena.challengee_video.user)%>
                    </td>
                  </tr>

                  <tr>
                    <td >Votes: <%= video.votes.count%>
                    </td>
                    <td >Votes: <%= public_arena.challengee_video.votes.count%>
                    </td>
                  </tr>

                  <tr>
                    <td colspan="2" class="index-view-btn">
                      <button type="button" class = "btn btn-index index-close"><%= link_to 'Review Battle', video_public_arena_path(video,video.public_arena_as_challenger) %></button>
                    </td>
                  </tr>

                </table>
            </li>
                  <% end %>

<% end %>

app/views/welcome/index.html.erb
<div class="row">

  <!--   <div class="col-md-6 col-md-offset-3"> -->


  <div class="window-in-window">
    <div class="wiw-group">
      <ul class="list-group">

        <li >
          <table id="index-video" class="table-responsive">
            <th id="index-status">TopThat Categories
            </th>
            <tr>
              <td class="index-open" >
                Awaiting A Challenger:
              </td>
            </tr>
            <tr>
              <td>
                <p>Enter the arena!<br>Upload a video to accept challenge</p>
              </td>
            </tr>
            <tr>
              <td class="index-in-battle" >
                In Battle:
              </td>
            </tr>
            <tr>
              <td>
                <p>View the arena!<br>Vote for your favorite video</p>
              </td>
            </tr>
            <tr>
              <td class="index-close" >
                Battles of Yesteryear:
              </td>
            </tr>
            <tr>
              <td>
                <p>Review the battle!<br>View previous battles</p>
              </td>
            </tr>

            <tr>
              <td  class="index-view-btn">
                <button type="button" class = "btn btn-index index-open"><%= link_to 'About TopThat', "/about" %></button>
              </td>
            </tr>

          </table>
        </li>

        <%@public_arenas.reverse.each do |arena|%>
        <% if arena.open? %>
        <li >
          <table id="index-video" class="table-responsive">
            <th id="index-status" class="index-open" colspan="2">AWAITING A CHALLENGER
            </th>
            <tr>
              <td style="height:27px"></td>
              <td></td>
            </tr>
            <tr>
              <td>
                <video width="120" height="60">
                  <source src= <%=arena.challenger_video.data_content %> type="video/mp4"/>
                  </video>
                </td>
                <td>
                  <div class="index-open-topthatlogo text-center">
                    <%= image_tag("topthatlogo3.png", width: "60", height: "60") %>
                  </div>
                </td>
              </tr>
              <tr>
                <td colspan="2" class="centered" >
                  <button type="button" class="versus round">VS</button>
                </td>
              </tr>
              <tr>
                <td><%= arena.challenger_video.title %></td>
                <td class="centered"><i>Can you top that?</i>
                </td>
              </tr>
              <tr>
                <td><%= image_tag(arena.challenger_video.user.avatar, width: "30", height: "30")%> <%= link_to arena.challenger_video.user.username, user_path(arena.challenger_video.user)%>
                </td>
                <td>
                </td>
              </tr>
             <tr>
              <td style="height:27px"></td>
              <td></td>
            </tr>
              <tr>
                <td colspan="2" class="index-view-btn">
                  <button type="button" class = "btn btn-index index-open"><%= link_to 'Step into the Arena', video_public_arena_path(arena.challenger_video, arena) %></button>
                </td>
              </tr>

            </table>
        </li>
          <% end %>


          <% if arena.in_battle? %>
        <li >
            <table id="index-video" class="table-responsive">
              <th id="index-status" class="index-in-battle" colspan="2">IN BATTLE
              </th>
              <tr>
                <td>
                  <video width="120" height="60">
                    <source src= <%=arena.challenger_video.data_content %> type="video/mp4"/>
                    </video>
                </td>
                <td>
                  <video width="120" height="60">
                    <source src= <%=arena.challengee_video.data_content %> type="video/mp4"/>
                      </video>
                </td>
              </tr>
              <tr>
                <td colspan="2" class="centered" >
                      <button type="button" class="versus round">VS</button>
                </td>
              </tr>
              <tr>
                <td><%= arena.challenger_video.title %></td>
                <td><%= arena.challengee_video.title %></td>
              </tr>
              <tr>
                <td><%= image_tag(arena.challenger_video.user.avatar, width: "30", height: "30")%> <%= link_to arena.challenger_video.user.username, user_path(arena.challenger_video.user)%>
                </td>
                <td><%= image_tag(arena.challengee_video.user.avatar, width: "30", height: "30")%> <%= link_to arena.challengee_video.user.username, user_path(arena.challengee_video.user)%>
                </td>
              </tr>
              <tr>
                <td>Votes: <%= arena.challenger_video.votes.count%>
                </td>
                <td>Votes: <%= arena.challengee_video.votes.count%>
                </td>
              </tr>
              <tr>
                <td colspan="2" class="index-view-btn">
                      <button type="button" class="btn btn-index index-in-battle"><%= link_to 'View Arena', video_public_arena_path(arena.challenger_video, arena) %></button>

                </td>
              </tr>

            </table>
        </li>
              <% end %>

              <% if arena.close? %>
        <li >
            <table id="index-video" class="table-responsive">
              <th id="index-status" class="index-close" colspan="2">CLOSED
              </th>
              <tr>
                <td class="index-winner" >
                  <% if arena.challenger_video.winner %> TopThat Winner!
                  <% elsif arena.tie? %><i>Tied</i>
                  <% end %>
                </td>
                <td class="index-winner" >
                  <% if arena.challengee_video.winner %> TopThat Winner!
                  <% elsif arena.tie? %><i>Tied</i>
                  <% end %>
                </td>
              </tr>

              <tr>
                <td>
                  <div class="wrapper">
                    <video width="120" height="60">
                      <source src= <%= arena.challenger_video.data_content %> type="video/mp4"/>
                      </video>
                    </div>
                  </td>
                  <td>
                    <div class="wrapper">
                      <video width="120" height="60">
                        <source src= <%= arena.challengee_video.data_content %> type="video/mp4"/>
                        </video>
                      </div>
                    </td>
                  </tr>

                  <tr>
                    <td colspan="2" class="centered" >
                      <button type="button" class="versus round">VS</button>
                    </td>
                  </tr>

                  <tr>
                    <td ><%= arena.challenger_video.title %></td>
                    <td ><%= arena.challengee_video.title %></td>
                  </tr>

                  <tr>
                    <td ><%= image_tag(arena.challenger_video.user.avatar, width: "30", height: "30")%> <%= link_to arena.challenger_video.user.username, user_path(arena.challenger_video.user)%>
                    </td>
                    <td ><%= image_tag(arena.challengee_video.user.avatar, width: "30", height: "30")%> <%= link_to arena.challengee_video.user.username, user_path(arena.challengee_video.user)%>
                    </td>
                  </tr>

                  <tr>
                    <td >Votes: <%= arena.challenger_video.votes.count%>
                    </td>
                    <td >Votes: <%= arena.challengee_video.votes.count%>
                    </td>
                  </tr>

                  <tr>
                    <td colspan="2" class="index-view-btn">
                      <button type="button" class = "btn btn-index index-close"><%= link_to 'Review Battle', video_public_arena_path(arena.challenger_video,arena.challenger_video.public_arena_as_challenger) %></button>
                    </td>
                  </tr>

                </table>
            </li>
                  <% end %>

                  <% end %>

          </ul>

        </div>
      </div><br><br>

      <div class="text-center">
              <%if @user %>
              <button type="button" class = "btn btn-challenge"><%= link_to 'challenge the world', new_user_video_path(@user, @video) %></button>
              <%else%>
              <button type="button" class = "btn btn-challenge"><%= link_to 'challenge the world', login_path %></button>
              <%end%>
    </div>

</div>

app/views/welcome/show.html.erb
<div class="row">
    <div class="window-in-window">
    <div class="wiw-group">
      <ul class="list-group">
      <%= render 'status' %>
      </ul>
    </div>
  </div><br><br>

  <div class="text-center">
              <%if @user %>
              <button type="button" class = "btn btn-challenge"><%= link_to 'challenge the world', new_user_video_path(@user, @video) %></button>
              <%else%>
              <button type="button" class = "btn btn-challenge"><%= link_to 'challenge the world', login_path %></button>
              <%end%>
  </div>

</div>

app/views/welcome/signin_login.html.erb
hello