config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  get    'signup'  => 'users#new'
  post   'users'   => 'users#create'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get '/public_arenas/:status' => 'welcome#show'
  get '/welcome' => 'welcome#index'
  get '/about' => 'about#index'

    resources :users do
      resources :videos, only: [:create, :new, :edit, :update, :destroy]
    end

    resources :videos do
      resources :votes
      resources :public_arenas, only: [:new, :edit, :create, :show, :update]
  end

  mount Sidekiq::Web, at: '/sidekiq'

  root 'sessions#index'

end

app/models/public_arena.rb
class PublicArena < ActiveRecord::Base
  belongs_to :challenger_video, class_name: "Video"
  belongs_to :challengee_video, class_name: "Video"


  def self.all_challenger_videos
    vidz = []
    Video.all.each { |vid| vidz << vid if  vid.public_arena_as_challenger != nil }
    vidz
  end

  def open?
    if self.challengee_video == nil
      true
    else
      false
    end
  end


  def in_battle?
    if self.challengee_video != nil && ((Time.now - self.updated_at)/60) < 30
      true
    else
      false
    end
  end

  def close?
    if self.challengee_video != nil && ((Time.now - self.updated_at)/60) >= 30
      true
    else
      false
    end
  end

  def challenger_won?
    if self.challenger_video && self.challengee_video && self.close?
      if self.challenger_video.votes.count > self.challengee_video.votes.count
        self.challenger_video.update_attributes(winner: true)
        true
      else
        false
      end
    end
  end

  def challengee_won?
    if self.challenger_video && self.challengee_video && self.close?
      if self.challengee_video.votes.count > self.challenger_video.votes.count
        self.challengee_video.update_attributes(winner: true)
        true
      else
        false
      end
    end
  end

  def tie?
    if self.challenger_video && self.challengee_video && self.close?
      if self.challengee_video.votes.count == self.challenger_video.votes.count
        true
      else
        false
      end
    end
  end

end

app/controllers/public_arenas_controller.rb
class PublicArenasController < ApplicationController

  def show
    # @user = current_user
    @public_arena = PublicArena.find(params[:id])
    @challenger_video = @public_arena.challenger_video
    @challenger = @challenger_video.user
    @challengee_video = @public_arena.challengee_video
    @vote = Vote.new
    @votes_for_challenger = @challenger_video.votes
    if @challengee_video
        @votes_for_challengee = @challengee_video.votes
        @challengee_user  = @challengee_video.user
    end
  end

  # def create
  #   @public_arena = PublicArena.create(public_arena_params)
  # end

  def edit
    if current_user
      @challenger_video = Video.find(params[:video_id])
      @public_arena = PublicArena.find(params[:id])
      @challengee_video =  Video.new
      if current_user == @challenger_video.user
        redirect_to video_public_arena_path(@challenger_video, @public_arena), alert: "You can't battle yourself!"
      end
    else
      redirect_to login_path
    end
  end


  def update
    @challengee_video = Video.create(user: current_user, title: params[:public_arena][:challengee_video], data_content: params[:public_arena][:challengee_video_id])
    @public_arena = PublicArena.find(params[:id])
    @public_arena.update_attributes(challengee_video: @challengee_video)
    AlertMailer.challenge_accepted_email(@public_arena).deliver_now
    AlertMailer.challenge_confirmation_email(@public_arena).deliver_now
    PublicArenaWorker.perform_in(30.minutes, @public_arena.id)
    redirect_to video_public_arena_path(@public_arena.challenger_video, @public_arena)
  end

  # def destroy
  #   @user = current_user
  #   @public_arena = PublicArena.find(params[:id])
  #   @public_arena.destroy!
  # end

private

   def public_arena_params
    params.require(:public_arena).permit(:challenger_video, :challengee_video, :status)
   end

end

app/views/public_arenas/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
<%=form_for ([@challenger_video, @public_arena]), :html => {:multipart => true} do |f|%>
    <%= f.label :challengee_video, "Title" %><br>
    <%= f.text_field :challengee_video, class: 'form-control'%><br><br>
    <%= f.label :challengee_video_id, "Add Video" %><br>
    <!-- challengee_video_id actually being passed as data_content -->
    <%= f.file_field :challengee_video_id  %><br><br>
    <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>
  </div>
</div>

app/views/public_arenas/edit.html.erb
 <%= render 'form' %>

app/views/public_arenas/show.html.erb
<!-- Go to www.addthis.com/dashboard to customize your tools -->
Share this battle! <div class="addthis_sharing_toolbox"></div>


<%if @public_arena.close? && @challengee_video %>
  <h5>Voting is now closed</h5>
<%elsif @public_arena.close? && @challengee_video == nil%>
  <h5>Arena is closed.</h5>
<%end%>



<%= @challenger_video.title %><br>

<div class=”jumbotron”>
<video width="320" height="240" controls>
      <source src= <%=@challenger_video.data_content %> type="video/mp4"/>
 Your browser does not support the video tag.
</video>
</div>

<%= image_tag(@challenger.avatar, width: "50", height: "50") %> <%= link_to @challenger.username, user_path(@challenger)%><br>

<% if @public_arena.in_battle? %>
    <div id= 'challenger_votes'><%= @challenger_video.votes.count%></div>
    <%= link_to image_tag("arrow_up.gif", width: "50"), video_votes_path(@challenger_video, @vote), id: "challenger_vote_link",  method: :post%><br><br>

    <%= link_to image_tag("arrow_down.gif", width: "50"), video_votes_path(@challengee_video, @vote), id: "challengee_vote_link", method: :post %><br>
    <div id= 'challengee_votes'><%= @challengee_video.votes.count%></div>
<%end%>

<% if @public_arena.close? %>
  <div id= 'challenger_votes'><%= @challenger_video.votes.count%></div>
    <%= image_tag("arrow_up.gif", width: "50")%><br><br>
    <%= image_tag("arrow_down.gif", width: "50")%><br>
  <div id= 'challengee_votes'><%= @challengee_video.votes.count%></div>
<%end%>

<%if @challengee_video%>

  <%= @challengee_video.title %><br>

<div class=”jumbotron”>
<video width="320" height="240" controls>
      <source src= <%=@challengee_video.data_content %> type="video/mp4"/>
 Your browser does not support the video tag.
</video>
</div>
<%= image_tag(@challengee_user.avatar, width: "50", height: "50")%> <%= link_to @challengee_user.username, user_path(@challengee_user)%>
<%end%>

<% if @public_arena.open? %>
    <%= link_to 'Step into the Arena', edit_video_public_arena_path(@challenger_video,@public_arena) %>
<%end%>